# Generated by Django 2.2.27 on 2022-04-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='NULL', max_length=254, verbose_name='邮箱'),
        ),
    ]
